name: Lean 4 Playground

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "lean4"
  lean4:
    name: Lean 4 Examples
    runs-on: ubuntu-latest
    steps:
      - name: install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.x
      - name: check
        run: |
          cd lean4
          ./install_deps.sh
          ./build.sh
          ./annotate_all.sh
          lake script run check_examples